import { Box, Button, Card, CardActions, CardContent, Container, Divider, IconButton, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import SettingsIcon from "@mui/icons-material/Settings";
import TuneIcon from "@mui/icons-material/Tune";
import PlayCircleIcon from "@mui/icons-material/PlayCircle";
import AddIcon from "@mui/icons-material/Add";

const Home: NextPage = () => {
  const sampleTasks = [
    {
      id: 1,
      time: "10:00",
      name: "My First Task",
      timeElapsed: "00:00",
    },
    {
      id: 2,
      time: "05:00",
      name: "Coffee Break",
      timeElapsed: "00:00",
    },
    {
      id: 3,
      time: "05:00",
      name: "A Really long title that will exceed the width of the container",
      timeElapsed: "00:00",
    },
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Container maxWidth="sm" sx={{ backgroundColor: "#fff", minHeight: "93vh" }}>
          <Box id="top-action-buttons" sx={{ display: "flex", justifyContent: "space-between", p: "1rem 0.5rem" }}>
            <SettingsIcon />
            <TuneIcon />
          </Box>

          <Box id="timer-container">
            <Typography variant="h3" align="center">
              10:00
            </Typography>
            <Typography variant="h6" align="center">
              My First Task
            </Typography>
            <Box id="timer-action-button" sx={{ display: "flex", justifyContent: "center", alignItems: "center" }}>
              <Typography variant="h6" sx={{ mr: "2.5rem" }}>
                -5
              </Typography>
              <IconButton>
                <PlayCircleIcon sx={{ fontSize: "4rem" }} />
              </IconButton>
              <Typography variant="h6" sx={{ ml: "2.5rem" }}>
                +5
              </Typography>
            </Box>
          </Box>

          <Box id="tasks-container" sx={{ width: "70%", mx: "auto" }}>
            {sampleTasks &&
              sampleTasks.map((task) => (
                <Card key={task.id} raised sx={{ my: "1rem", p: "0.5rem" }}>
                  <Box sx={{ display: "flex", alignItems: "center" }}>
                    <Box id="task-time-container" sx={{ p: "0.5rem" }}>
                      <Typography variant="h6" align="center">
                        {task.time}
                      </Typography>
                    </Box>
                    <Box
                      id="task-data-container"
                      sx={{
                        flex: 1,
                        display: "flex",
                        p: "0rem 0.5rem",
                        flexDirection: "column",
                        justifyContent: "space-between",
                        width: "20%",
                      }}
                    >
                      <Typography noWrap sx={{ px: "0.5rem", pt: "0.5rem" }}>
                        {task.name}
                      </Typography>
                      <Divider sx={{ mt: "1rem", mb: "0.5rem" }} />
                      <Box
                        id="task-action-buttons"
                        sx={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}
                      >
                        <Button size="small">Delete</Button>
                        <Button size="small">Reset</Button>
                        <Button size="small">Complete</Button>
                        <Typography sx={{ background: "lightGray", p: "0.3rem", borderRadius: "0.5rem" }}>
                          {task.timeElapsed}
                        </Typography>
                      </Box>
                    </Box>
                  </Box>
                </Card>
              ))}
          </Box>

          <Box
            id="add-task-container"
            sx={{
              width: "70%",
              mx: "auto",
              background: "lightGray",
              borderRadius: "0.5rem",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              border: "2px dashed gray",
              height: "106.6px",
            }}
          >
            <AddIcon sx={{ color: "text.secondary" }} />
            <Typography color="textSecondary">Add Task</Typography>
          </Box>

          <Box
            id="button-action-buttons"
            sx={{ width: "70%", mx: "auto", display: "flex", justifyContent: "space-between" }}
          >
            <Typography color="textSecondary" variant="subtitle2">
              Hide Completed
            </Typography>
            <Typography color="textSecondary" variant="subtitle2">
              Clear All
            </Typography>
            <Typography color="textSecondary" variant="subtitle2">
              Clear Completed
            </Typography>
          </Box>
        </Container>
      </>
    </div>
  );
};

export default Home;
