import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import AddTask from "../components/AddTask";
import TasksContainer from "../components/TasksContainer";
import Timer from "../components/Timer";
import TopActionButtons from "../components/TopActionButtons";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>aloeviate.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>
        <Container maxWidth="sm" sx={{ background: "#f5f5f5", minHeight: "93vh" }}>
          <TopActionButtons />
          <Timer />
          <TasksContainer />
          <AddTask />
        </Container>
      </>
    </div>
  );
};

export default Home;
